# Generated by Django 5.1.6 on 2025-03-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SINAC", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estudiante",
            name="curso",
        ),
        migrations.AddField(
            model_name="profesor",
            name="documento",
            field=models.CharField(default="0000000000", max_length=20, unique=True),
        ),
    ]
