# Generated by Django 5.1.6 on 2025-03-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SINAC", "0004_remove_profesor_asignatura"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profesor",
            name="correo",
        ),
        migrations.RemoveField(
            model_name="profesor",
            name="documento",
        ),
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("ADMINISTRADOR", "Administrador"),
                    ("ESTUDIANTE", "Estudiante"),
                    ("profesor", "Profesor"),
                ],
                default="ESTUDIANTE",
                max_length=20,
            ),
        ),
    ]
