# Generated by Django 5.1.6 on 2025-03-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SINAC", "0005_remove_profesor_correo_remove_profesor_documento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profesor",
            name="documento",
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profesor",
            name="email",
            field=models.EmailField(
                default="correo@med.co", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
    ]
