# Generated by Django 5.1.6 on 2025-03-05 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SINAC", "0009_estudiante_grupo"),
    ]

    operations = [
        migrations.AddField(
            model_name="asignatura",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="SINAC.grupo",
            ),
        ),
    ]
