# Generated by Django 5.1.6 on 2025-03-05 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SINAC", "0010_asignatura_grupo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asignatura",
            name="profesor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asignaturas",
                to="SINAC.profesor",
            ),
        ),
    ]
