# Generated by Django 5.1.6 on 2025-03-05 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SINAC", "0011_alter_asignatura_profesor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asignatura",
            name="profesor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="SINAC.profesor"
            ),
        ),
    ]
