# Generated by Django 5.1.6 on 2025-03-07 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SINAC", "0012_alter_asignatura_profesor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nota",
            name="curso",
        ),
        migrations.AddField(
            model_name="nota",
            name="asignatura",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="SINAC.asignatura",
            ),
            preserve_default=False,
        ),
    ]
